### ISSUE TITLE
Remove workbox-google-analytics

### ISSUE THREAD

**Issue by vilsbole** [MyCryptoHQ/landing#19]
`gatsby-plugin-offline` include `workbox-google-analytics`.
Do we really need this plugin?
If so, let's find a way to  exclude `workbox-google-analytics` from the package.

**Comment by GuillaumeRx** [comment]
@vilsbole can you create a Card for this please ?

**Comment by vilsbole** [comment]
Closing in favour of: https://app.clubhouse.io/mycrypto/story/6759/landing-remove-workbox-google-analytics
